spring:
  application:
    name: Journal App

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "768353140216-pkvrbg1qh7c2jihl8p1kubf00sdcqspn.apps.googleusercontent.com"
            client-secret: "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"
  #            client-id: ${GOOGLE_CLIENT_ID}
  #            client-secret: ${GOOGLE_CLIENT_SECRET}

  data:
    mongodb:
      uri: mongodb+srv://borkhatariyadipak24:mfaxm3x0odL9kuEC@cluster0.ihorrrx.mongodb.net/journaldb?retryWrites=true&w=majority&appName=Cluster0
      database: journaldb
      auto-index-creation: true

    redis:
      host: redis-13705.crce206.ap-south-1-1.ec2.redns.redis-cloud.com
      port: 13705
      password: sSaAZa5VIhM0Lo3Rq5EonznAWMm9sVE9

  mail:
    host: smtp.gmail.com
    port: 587
    username: borkhatariyadipak24@gmail.com
    password: cedl mndb wevd ebam
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true



server:
  port: 8081
  servlet:
    context-path: /journal

logging:
  file:
    name: logs/journalApp.log

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

weather:
  api:
    key: "4e0f5ee0ff2e7399b33dea1632440101"